version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/MetaDataTransformer"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/MetaDataTransformerUsage"
    update_schedule: "live"